2021-10-13 08:54:12.445398 (MainThread): Running with dbt=0.21.0
2021-10-13 08:54:17.546372 (MainThread): running dbt with arguments Namespace(record_timing_info=None, debug=False, log_format='default', write_json=True, use_colors=None, strict=False, warn_error=False, partial_parse=None, single_threaded=False, test_new_parser=False, use_experimental_parser=False, project_dir=None, profiles_dir='/Users/zoltancsonka/.dbt', profile=None, target=None, vars='{}', log_cache_events=False, use_cache=True, full_refresh=False, show=False, threads=None, version_check=True, select=None, exclude=None, selector_name=None, state=None, defer=None, cls=<class 'dbt.task.seed.SeedTask'>, which='seed', rpc_method='seed')
2021-10-13 08:54:17.549713 (MainThread): Tracking: tracking
2021-10-13 08:54:17.550337 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10abbf5e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10abbfc10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10abaf760>]}
2021-10-13 08:54:17.604199 (MainThread): Partial parsing not enabled
2021-10-13 08:54:18.080073 (MainThread): Parsing macros/catalog.sql
2021-10-13 08:54:18.083220 (MainThread): Parsing macros/adapters.sql
2021-10-13 08:54:18.150149 (MainThread): Parsing macros/materializations/merge.sql
2021-10-13 08:54:18.155725 (MainThread): Parsing macros/materializations/seed.sql
2021-10-13 08:54:18.161614 (MainThread): Parsing macros/materializations/view.sql
2021-10-13 08:54:18.163366 (MainThread): Parsing macros/materializations/table.sql
2021-10-13 08:54:18.167214 (MainThread): Parsing macros/materializations/incremental.sql
2021-10-13 08:54:18.178690 (MainThread): Parsing macros/core.sql
2021-10-13 08:54:18.183509 (MainThread): Parsing macros/materializations/test.sql
2021-10-13 08:54:18.192346 (MainThread): Parsing macros/materializations/helpers.sql
2021-10-13 08:54:18.203838 (MainThread): Parsing macros/materializations/snapshot/snapshot_merge.sql
2021-10-13 08:54:18.206413 (MainThread): Parsing macros/materializations/snapshot/strategies.sql
2021-10-13 08:54:18.226420 (MainThread): Parsing macros/materializations/snapshot/snapshot.sql
2021-10-13 08:54:18.259605 (MainThread): Parsing macros/materializations/seed/seed.sql
2021-10-13 08:54:18.283023 (MainThread): Parsing macros/materializations/incremental/helpers.sql
2021-10-13 08:54:18.284845 (MainThread): Parsing macros/materializations/incremental/incremental.sql
2021-10-13 08:54:18.295530 (MainThread): Parsing macros/materializations/incremental/on_schema_change.sql
2021-10-13 08:54:18.316025 (MainThread): Parsing macros/materializations/common/merge.sql
2021-10-13 08:54:18.330586 (MainThread): Parsing macros/materializations/table/table.sql
2021-10-13 08:54:18.338413 (MainThread): Parsing macros/materializations/view/view.sql
2021-10-13 08:54:18.345750 (MainThread): Parsing macros/materializations/view/create_or_replace_view.sql
2021-10-13 08:54:18.349741 (MainThread): Parsing macros/etc/get_custom_alias.sql
2021-10-13 08:54:18.351295 (MainThread): Parsing macros/etc/query.sql
2021-10-13 08:54:18.352391 (MainThread): Parsing macros/etc/is_incremental.sql
2021-10-13 08:54:18.353951 (MainThread): Parsing macros/etc/datetime.sql
2021-10-13 08:54:18.362818 (MainThread): Parsing macros/etc/where_subquery.sql
2021-10-13 08:54:18.364677 (MainThread): Parsing macros/etc/get_custom_schema.sql
2021-10-13 08:54:18.367145 (MainThread): Parsing macros/etc/get_custom_database.sql
2021-10-13 08:54:18.368756 (MainThread): Parsing macros/adapters/common.sql
2021-10-13 08:54:18.424040 (MainThread): Parsing macros/schema_tests/relationships.sql
2021-10-13 08:54:18.425813 (MainThread): Parsing macros/schema_tests/not_null.sql
2021-10-13 08:54:18.427033 (MainThread): Parsing macros/schema_tests/unique.sql
2021-10-13 08:54:18.428402 (MainThread): Parsing macros/schema_tests/accepted_values.sql
2021-10-13 08:54:18.629867 (MainThread): Acquiring new snowflake connection "model.sqlfluff.test".
2021-10-13 08:54:18.643780 (MainThread): Acquiring new snowflake connection "model.sqlfluff.dim_customer".
2021-10-13 08:54:18.720691 (MainThread): Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'b183ddcd-98bd-4fec-812c-1b0647e435ff', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b2d1c10>]}
2021-10-13 08:54:18.726779 (MainThread): write_gpickle is deprecated and will be removed in 3.0.Use ``pickle.dump(G, path, protocol)``
2021-10-13 08:54:18.727353 (MainThread): Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'b183ddcd-98bd-4fec-812c-1b0647e435ff', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b2d1910>]}
2021-10-13 08:54:18.727842 (MainThread): Found 2 models, 0 tests, 0 snapshots, 0 analyses, 172 macros, 0 operations, 0 seed files, 0 sources, 0 exposures
2021-10-13 08:54:18.729385 (MainThread): 
WARNING: Nothing to do. Try checking your model configs and model specification args
2021-10-13 08:54:18.755131 (MainThread): 
2021-10-13 08:54:18.755612 (MainThread): Completed successfully
2021-10-13 08:54:18.755865 (MainThread): 
Done. PASS=0 WARN=0 ERROR=0 SKIP=0 TOTAL=0
2021-10-13 08:54:18.756377 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b2d1520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b2d1f70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b2d1f10>]}
2021-10-13 08:54:18.756784 (MainThread): Flushing usage events
2021-10-13 08:54:19.337553 (MainThread): Connection 'model.sqlfluff.dim_customer' was properly closed.
2021-10-13 10:49:35.102684 (MainThread): Running with dbt=0.21.0
2021-10-13 10:49:37.277570 (MainThread): running dbt with arguments Namespace(record_timing_info=None, debug=False, log_format='default', write_json=True, use_colors=None, strict=False, warn_error=False, partial_parse=None, single_threaded=False, test_new_parser=False, use_experimental_parser=False, project_dir=None, profiles_dir='/Users/zoltancsonka/.dbt', profile=None, target=None, vars='{}', log_cache_events=False, use_cache=True, fail_fast=False, threads=None, version_check=True, select=None, exclude=None, selector_name=None, state=None, defer=None, full_refresh=False, cls=<class 'dbt.task.run.RunTask'>, which='run', rpc_method='run')
2021-10-13 10:49:37.280155 (MainThread): Tracking: tracking
2021-10-13 10:49:37.280787 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1102903a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110290a30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11027f8b0>]}
2021-10-13 10:49:37.327353 (MainThread): Partial parsing not enabled
2021-10-13 10:49:37.383607 (MainThread): Parsing macros/catalog.sql
2021-10-13 10:49:37.386700 (MainThread): Parsing macros/adapters.sql
2021-10-13 10:49:37.448493 (MainThread): Parsing macros/materializations/merge.sql
2021-10-13 10:49:37.453945 (MainThread): Parsing macros/materializations/seed.sql
2021-10-13 10:49:37.459922 (MainThread): Parsing macros/materializations/view.sql
2021-10-13 10:49:37.461727 (MainThread): Parsing macros/materializations/table.sql
2021-10-13 10:49:37.465610 (MainThread): Parsing macros/materializations/incremental.sql
2021-10-13 10:49:37.476763 (MainThread): Parsing macros/core.sql
2021-10-13 10:49:37.481398 (MainThread): Parsing macros/materializations/test.sql
2021-10-13 10:49:37.489730 (MainThread): Parsing macros/materializations/helpers.sql
2021-10-13 10:49:37.502603 (MainThread): Parsing macros/materializations/snapshot/snapshot_merge.sql
2021-10-13 10:49:37.504730 (MainThread): Parsing macros/materializations/snapshot/strategies.sql
2021-10-13 10:49:37.526642 (MainThread): Parsing macros/materializations/snapshot/snapshot.sql
2021-10-13 10:49:37.564343 (MainThread): Parsing macros/materializations/seed/seed.sql
2021-10-13 10:49:37.588921 (MainThread): Parsing macros/materializations/incremental/helpers.sql
2021-10-13 10:49:37.590725 (MainThread): Parsing macros/materializations/incremental/incremental.sql
2021-10-13 10:49:37.601132 (MainThread): Parsing macros/materializations/incremental/on_schema_change.sql
2021-10-13 10:49:37.621668 (MainThread): Parsing macros/materializations/common/merge.sql
2021-10-13 10:49:37.636092 (MainThread): Parsing macros/materializations/table/table.sql
2021-10-13 10:49:37.644271 (MainThread): Parsing macros/materializations/view/view.sql
2021-10-13 10:49:37.651839 (MainThread): Parsing macros/materializations/view/create_or_replace_view.sql
2021-10-13 10:49:37.655940 (MainThread): Parsing macros/etc/get_custom_alias.sql
2021-10-13 10:49:37.657543 (MainThread): Parsing macros/etc/query.sql
2021-10-13 10:49:37.658539 (MainThread): Parsing macros/etc/is_incremental.sql
2021-10-13 10:49:37.660072 (MainThread): Parsing macros/etc/datetime.sql
2021-10-13 10:49:37.669138 (MainThread): Parsing macros/etc/where_subquery.sql
2021-10-13 10:49:37.671227 (MainThread): Parsing macros/etc/get_custom_schema.sql
2021-10-13 10:49:37.673965 (MainThread): Parsing macros/etc/get_custom_database.sql
2021-10-13 10:49:37.675705 (MainThread): Parsing macros/adapters/common.sql
2021-10-13 10:49:37.736003 (MainThread): Parsing macros/schema_tests/relationships.sql
2021-10-13 10:49:37.737855 (MainThread): Parsing macros/schema_tests/not_null.sql
2021-10-13 10:49:37.739144 (MainThread): Parsing macros/schema_tests/unique.sql
2021-10-13 10:49:37.740571 (MainThread): Parsing macros/schema_tests/accepted_values.sql
2021-10-13 10:49:37.950169 (MainThread): Acquiring new snowflake connection "model.sqlfluff.test".
2021-10-13 10:49:37.964860 (MainThread): Acquiring new snowflake connection "model.sqlfluff.dim_customer".
2021-10-13 10:49:38.047823 (MainThread): Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'ea1d7fb9-c4bf-435a-86c5-760777a191a1', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110370c10>]}
2021-10-13 10:49:38.071060 (MainThread): write_gpickle is deprecated and will be removed in 3.0.Use ``pickle.dump(G, path, protocol)``
2021-10-13 10:49:38.072216 (MainThread): Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'ea1d7fb9-c4bf-435a-86c5-760777a191a1', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110370580>]}
2021-10-13 10:49:38.072939 (MainThread): Found 2 models, 0 tests, 0 snapshots, 0 analyses, 172 macros, 0 operations, 0 seed files, 0 sources, 0 exposures
2021-10-13 10:49:38.074902 (MainThread): 
2021-10-13 10:49:38.075662 (MainThread): Acquiring new snowflake connection "master".
2021-10-13 10:49:38.076864 (ThreadPoolExecutor-0_0): Acquiring new snowflake connection "list_DV_PROTOTYPE_DB".
2021-10-13 10:49:38.094999 (ThreadPoolExecutor-0_0): Using snowflake connection "list_DV_PROTOTYPE_DB".
2021-10-13 10:49:38.095267 (ThreadPoolExecutor-0_0): On list_DV_PROTOTYPE_DB: /* {"app": "dbt", "dbt_version": "0.21.0", "profile_name": "fission", "target_name": "dev", "connection_name": "list_DV_PROTOTYPE_DB"} */

    show terse schemas in database DV_PROTOTYPE_DB
    limit 10000
2021-10-13 10:49:38.095469 (ThreadPoolExecutor-0_0): Opening a new connection, currently in state init
2021-10-13 10:49:39.418362 (ThreadPoolExecutor-0_0): SQL status: SUCCESS 6 in 1.32 seconds
2021-10-13 10:49:39.420441 (ThreadPoolExecutor-0_0): On list_DV_PROTOTYPE_DB: Close
2021-10-13 10:49:39.862641 (ThreadPoolExecutor-1_0): Acquiring new snowflake connection "list_DV_PROTOTYPE_DB_DEMO".
2021-10-13 10:49:39.872000 (ThreadPoolExecutor-1_0): Using snowflake connection "list_DV_PROTOTYPE_DB_DEMO".
2021-10-13 10:49:39.872293 (ThreadPoolExecutor-1_0): On list_DV_PROTOTYPE_DB_DEMO: /* {"app": "dbt", "dbt_version": "0.21.0", "profile_name": "fission", "target_name": "dev", "connection_name": "list_DV_PROTOTYPE_DB_DEMO"} */

    show terse objects in DV_PROTOTYPE_DB.DEMO
2021-10-13 10:49:39.872536 (ThreadPoolExecutor-1_0): Opening a new connection, currently in state closed
2021-10-13 10:49:40.717987 (ThreadPoolExecutor-1_0): SQL status: SUCCESS 0 in 0.85 seconds
2021-10-13 10:49:40.719509 (ThreadPoolExecutor-1_0): On list_DV_PROTOTYPE_DB_DEMO: Close
2021-10-13 10:49:40.921251 (MainThread): 12:49:40 | Concurrency: 4 threads (target='dev')
2021-10-13 10:49:40.921574 (MainThread): 12:49:40 | 
2021-10-13 10:49:40.922975 (Thread-1): Began running node model.sqlfluff.dim_customer
2021-10-13 10:49:40.923229 (Thread-2): Began running node model.sqlfluff.test
2021-10-13 10:49:40.923632 (Thread-1): 12:49:40 | 1 of 2 START view model DEMO.dim_customer............................ [RUN]
2021-10-13 10:49:40.923975 (Thread-2): 12:49:40 | 2 of 2 START view model DEMO.test.................................... [RUN]
2021-10-13 10:49:40.924437 (Thread-1): Acquiring new snowflake connection "model.sqlfluff.dim_customer".
2021-10-13 10:49:40.924853 (Thread-2): Acquiring new snowflake connection "model.sqlfluff.test".
2021-10-13 10:49:40.925056 (Thread-1): Compiling model.sqlfluff.dim_customer
2021-10-13 10:49:40.925278 (Thread-2): Compiling model.sqlfluff.test
2021-10-13 10:49:40.927007 (Thread-1): Writing injected SQL for node "model.sqlfluff.dim_customer"
2021-10-13 10:49:40.928338 (Thread-2): Writing injected SQL for node "model.sqlfluff.test"
2021-10-13 10:49:40.929939 (Thread-2): finished collecting timing info
2021-10-13 10:49:40.930173 (Thread-1): finished collecting timing info
2021-10-13 10:49:40.975740 (Thread-1): Writing runtime SQL for node "model.sqlfluff.dim_customer"
2021-10-13 10:49:40.976172 (Thread-2): Writing runtime SQL for node "model.sqlfluff.test"
2021-10-13 10:49:40.977757 (Thread-2): Using snowflake connection "model.sqlfluff.test".
2021-10-13 10:49:40.978410 (Thread-1): Using snowflake connection "model.sqlfluff.dim_customer".
2021-10-13 10:49:40.978628 (Thread-2): On model.sqlfluff.test: /* {"app": "dbt", "dbt_version": "0.21.0", "profile_name": "fission", "target_name": "dev", "node_id": "model.sqlfluff.test"} */

  create or replace  view DV_PROTOTYPE_DB.DEMO.test  as (
    SELECT
    c AS bar,
    a + b AS foo
FROM my_table
  );
2021-10-13 10:49:40.978837 (Thread-1): On model.sqlfluff.dim_customer: /* {"app": "dbt", "dbt_version": "0.21.0", "profile_name": "fission", "target_name": "dev", "node_id": "model.sqlfluff.dim_customer"} */

  create or replace  view DV_PROTOTYPE_DB.DEMO.dim_customer  as (
    select
    customer.dim_customer_id,
    customer.customer_name,
    customer.is_active,
    customer.created_at
from customer
  );
2021-10-13 10:49:40.979048 (Thread-2): Opening a new connection, currently in state init
2021-10-13 10:49:40.979283 (Thread-1): Opening a new connection, currently in state closed
2021-10-13 10:49:41.932150 (Thread-2): Snowflake query id: 019f9429-3200-edd5-0000-265902293546
2021-10-13 10:49:41.932424 (Thread-2): Snowflake error: 002003 (42S02): SQL compilation error:
Object 'DV_PROTOTYPE_DB.DEMO.MY_TABLE' does not exist or not authorized.
2021-10-13 10:49:41.932723 (Thread-2): finished collecting timing info
2021-10-13 10:49:41.932969 (Thread-2): On model.sqlfluff.test: Close
2021-10-13 10:49:41.984783 (Thread-1): Snowflake query id: 019f9429-3200-edf0-0000-265902296146
2021-10-13 10:49:41.985044 (Thread-1): Snowflake error: 002003 (42S02): SQL compilation error:
Object 'DV_PROTOTYPE_DB.DEMO.CUSTOMER' does not exist or not authorized.
2021-10-13 10:49:41.985296 (Thread-1): finished collecting timing info
2021-10-13 10:49:41.985535 (Thread-1): On model.sqlfluff.dim_customer: Close
2021-10-13 10:49:42.128036 (Thread-2): Database Error in model test (models/test.sql)
  002003 (42S02): SQL compilation error:
  Object 'DV_PROTOTYPE_DB.DEMO.MY_TABLE' does not exist or not authorized.
  compiled SQL at target/run/sqlfluff/models/test.sql
Traceback (most recent call last):
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/adapters/snowflake/connections.py", line 183, in exception_handler
    yield
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/adapters/sql/connections.py", line 80, in add_query
    cursor.execute(sql, bindings)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/snowflake/connector/cursor.py", line 721, in execute
    Error.errorhandler_wrapper(
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/snowflake/connector/errors.py", line 258, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/snowflake/connector/errors.py", line 188, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002003 (42S02): SQL compilation error:
Object 'DV_PROTOTYPE_DB.DEMO.MY_TABLE' does not exist or not authorized.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/task/base.py", line 348, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/task/base.py", line 291, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/task/base.py", line 393, in run
    return self.execute(compiled_node, manifest)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/task/run.py", line 249, in execute
    result = MacroGenerator(materialization_macro, context)()
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/clients/jinja.py", line 333, in __call__
    return self.call_macro(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/clients/jinja.py", line 260, in call_macro
    return macro(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 27, in macro
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/clients/jinja.py", line 333, in __call__
    return self.call_macro(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/clients/jinja.py", line 260, in call_macro
    return macro(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 55, in macro
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/clients/jinja.py", line 333, in __call__
    return self.call_macro(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/clients/jinja.py", line 260, in call_macro
    return macro(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 41, in macro
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/adapters/base/impl.py", line 226, in execute
    return self.connections.execute(
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/adapters/sql/connections.py", line 131, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/adapters/snowflake/connections.py", line 354, in add_query
    connection, cursor = super().add_query(
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/adapters/sql/connections.py", line 87, in add_query
    return connection, cursor
  File "/Users/zoltancsonka/.pyenv/versions/3.9.1/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/adapters/snowflake/connections.py", line 200, in exception_handler
    raise DatabaseException(msg)
dbt.exceptions.DatabaseException: Database Error in model test (models/test.sql)
  002003 (42S02): SQL compilation error:
  Object 'DV_PROTOTYPE_DB.DEMO.MY_TABLE' does not exist or not authorized.
  compiled SQL at target/run/sqlfluff/models/test.sql
2021-10-13 10:49:42.133433 (Thread-2): Sending event: {'category': 'dbt', 'action': 'run_model', 'label': 'ea1d7fb9-c4bf-435a-86c5-760777a191a1', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110370ac0>]}
2021-10-13 10:49:42.133897 (Thread-2): 12:49:42 | 2 of 2 ERROR creating view model DEMO.test........................... [ERROR in 1.21s]
2021-10-13 10:49:42.134149 (Thread-2): Finished running node model.sqlfluff.test
2021-10-13 10:49:42.206079 (Thread-1): Database Error in model dim_customer (models/dim_customer.sql)
  002003 (42S02): SQL compilation error:
  Object 'DV_PROTOTYPE_DB.DEMO.CUSTOMER' does not exist or not authorized.
  compiled SQL at target/run/sqlfluff/models/dim_customer.sql
Traceback (most recent call last):
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/adapters/snowflake/connections.py", line 183, in exception_handler
    yield
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/adapters/sql/connections.py", line 80, in add_query
    cursor.execute(sql, bindings)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/snowflake/connector/cursor.py", line 721, in execute
    Error.errorhandler_wrapper(
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/snowflake/connector/errors.py", line 258, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/snowflake/connector/errors.py", line 188, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002003 (42S02): SQL compilation error:
Object 'DV_PROTOTYPE_DB.DEMO.CUSTOMER' does not exist or not authorized.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/task/base.py", line 348, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/task/base.py", line 291, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/task/base.py", line 393, in run
    return self.execute(compiled_node, manifest)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/task/run.py", line 249, in execute
    result = MacroGenerator(materialization_macro, context)()
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/clients/jinja.py", line 333, in __call__
    return self.call_macro(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/clients/jinja.py", line 260, in call_macro
    return macro(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 27, in macro
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/clients/jinja.py", line 333, in __call__
    return self.call_macro(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/clients/jinja.py", line 260, in call_macro
    return macro(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 55, in macro
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/clients/jinja.py", line 333, in __call__
    return self.call_macro(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/clients/jinja.py", line 260, in call_macro
    return macro(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 41, in macro
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/adapters/base/impl.py", line 226, in execute
    return self.connections.execute(
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/adapters/sql/connections.py", line 131, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/adapters/snowflake/connections.py", line 354, in add_query
    connection, cursor = super().add_query(
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/adapters/sql/connections.py", line 87, in add_query
    return connection, cursor
  File "/Users/zoltancsonka/.pyenv/versions/3.9.1/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/zoltancsonka/.pyenv/versions/sqlfluff/lib/python3.9/site-packages/dbt/adapters/snowflake/connections.py", line 200, in exception_handler
    raise DatabaseException(msg)
dbt.exceptions.DatabaseException: Database Error in model dim_customer (models/dim_customer.sql)
  002003 (42S02): SQL compilation error:
  Object 'DV_PROTOTYPE_DB.DEMO.CUSTOMER' does not exist or not authorized.
  compiled SQL at target/run/sqlfluff/models/dim_customer.sql
2021-10-13 10:49:42.207035 (Thread-1): Sending event: {'category': 'dbt', 'action': 'run_model', 'label': 'ea1d7fb9-c4bf-435a-86c5-760777a191a1', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110d1c7f0>]}
2021-10-13 10:49:42.207460 (Thread-1): 12:49:42 | 1 of 2 ERROR creating view model DEMO.dim_customer................... [ERROR in 1.28s]
2021-10-13 10:49:42.207703 (Thread-1): Finished running node model.sqlfluff.dim_customer
2021-10-13 10:49:42.208938 (MainThread): Acquiring new snowflake connection "master".
2021-10-13 10:49:42.209381 (MainThread): 12:49:42 | 
2021-10-13 10:49:42.209625 (MainThread): 12:49:42 | Finished running 2 view models in 4.13s.
2021-10-13 10:49:42.209864 (MainThread): Connection 'master' was properly closed.
2021-10-13 10:49:42.210066 (MainThread): Connection 'model.sqlfluff.dim_customer' was properly closed.
2021-10-13 10:49:42.210241 (MainThread): Connection 'model.sqlfluff.test' was properly closed.
2021-10-13 10:49:42.222730 (MainThread): 
2021-10-13 10:49:42.223099 (MainThread): Completed with 2 errors and 0 warnings:
2021-10-13 10:49:42.223351 (MainThread): 
2021-10-13 10:49:42.223656 (MainThread): Database Error in model test (models/test.sql)
2021-10-13 10:49:42.224052 (MainThread):   002003 (42S02): SQL compilation error:
2021-10-13 10:49:42.224287 (MainThread):   Object 'DV_PROTOTYPE_DB.DEMO.MY_TABLE' does not exist or not authorized.
2021-10-13 10:49:42.224501 (MainThread):   compiled SQL at target/run/sqlfluff/models/test.sql
2021-10-13 10:49:42.224724 (MainThread): 
2021-10-13 10:49:42.224951 (MainThread): Database Error in model dim_customer (models/dim_customer.sql)
2021-10-13 10:49:42.225173 (MainThread):   002003 (42S02): SQL compilation error:
2021-10-13 10:49:42.225393 (MainThread):   Object 'DV_PROTOTYPE_DB.DEMO.CUSTOMER' does not exist or not authorized.
2021-10-13 10:49:42.225596 (MainThread):   compiled SQL at target/run/sqlfluff/models/dim_customer.sql
2021-10-13 10:49:42.225817 (MainThread): 
Done. PASS=0 WARN=0 ERROR=2 SKIP=0 TOTAL=2
2021-10-13 10:49:42.226168 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110323610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1103235e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110323580>]}
2021-10-13 10:49:42.226492 (MainThread): Flushing usage events
